### ISSUE TITLE
Prometheus不能监控到k8s集群里面的etcd

### ISSUE THREAD

**Issue by ppabc** [cuishuaigit/k8s-monitor#1]
6.修改core-configmap里的etcd地址
这个地方修改了，提示无法连接etcd
是不是还有其他步骤没写？

**Comment by ppabc** [comment]
没有etc证书验证，貌似不能连接监控

**Comment by cuishuaigit** [comment]
@ppabc 
这里漏更了，现在已经修改了core-configmap.忽略证书检测。或者直接把证书加到配置文件里面
- job_name: 'etcd'
          scheme: https
          insecure_skip_verify: true
          static_configs:
